version: '2'
services:
  backend:
    build: ./backend
    volumes:
      - recording-storage:/recording-storage
    environment:
      - VIRTUAL_HOST=backend.localhost
    depends_on:
      - rest
  rest:
    build:
      context: ./rest
    volumes:
      - ./migrations:/migrations
    depends_on:
      - recording_db
    environment:
      - VIRTUAL_HOST=rest.localhost
  recording_db:
    image: postgres
  static:
    image: nginx
    volumes:
      - recording-storage:/usr/share/nginx/html/storage
      - ./example:/usr/share/nginx/html/example
      - ./admin:/usr/share/nginx/html/admin
    environment:
      - VIRTUAL_HOST=static.localhost
  frontend:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=static.localhost
volumes:
  recording-storage: {}
